name: Build an executable fat JAR file for the lab3 module

on:
  push:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file lab3/pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lab3-jar
          path: lab3/target/lab3-1.0-SNAPSHOT.jar
